[package]
name = "pathfinder"
version = "0.1.0"
authors = ["Kol Crooks <kolcrooks10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
rand = "0.8.3"
image = "0.23.14"